"""empty message

Revision ID: 450745d4ea05
Revises: e16234738037
Create Date: 2017-03-12 17:42:46.173850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450745d4ea05'
down_revision = 'e16234738037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'user_profile_bio_key', 'user_profile', type_='unique')
    op.drop_constraint(u'user_profile_gender_key', 'user_profile', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'user_profile_gender_key', 'user_profile', ['gender'])
    op.create_unique_constraint(u'user_profile_bio_key', 'user_profile', ['bio'])
    # ### end Alembic commands ###
