"""empty message

Revision ID: d210283a2b28
Revises: f7373f2ba718
Create Date: 2017-03-13 00:37:38.699933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd210283a2b28'
down_revision = 'f7373f2ba718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_profile', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='unique')
    # ### end Alembic commands ###
