"""empty message

Revision ID: f7373f2ba718
Revises: 450745d4ea05
Create Date: 2017-03-12 20:52:16.676632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7373f2ba718'
down_revision = '450745d4ea05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('username', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'user_profile', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.drop_column('user_profile', 'username')
    # ### end Alembic commands ###
